lang: pt

format:
  html:
    include-in-header:
      text: |
        <style>.blog-section-es, .blog-section-en { display: none !important; }</style>

project:
  output-dir: docs/pt

website:
  navbar:
    left:
      - href: /index.html
        text: "**PT**"
      - href: ../en/index.html
        text: EN  
      - href: ../index.html
        text: ES      
      - text: "Página inicial"
        href: /index.html
      # - text: Participe
      #   menu: 
      #      - text: "Chamada para submissão de trabalhos"
      #        href: blog/pt/2026-06-03-segunda-extensao-prazo.html
         # - text: "Sobre a inscrição"
         #   href: blog/pt/2024-08-01-inscricao.qmd
        # - text: "Inscrição"
         #  href: https://www.eventbrite.com.ar/e/1939670499679?aff=oddtdtcreator
      - text: "Inscrição"
        menu:
          - text: "Informações de inscrição"
            href: blog/pt/2026-08-25-inscricao.html
          - text: "Inscreva-se no Eventbrite"
            href: https://www.eventbrite.com.ar/e/1998690018649

      - text: LatinR 2026
        menu: 
          - text: "Localização"
            href: cronograma/lugar/lugar-pt.qmd    
          - text: "Recursos turísticos"
            href: cronograma/recursos-turisticos/index-pt.qmd  
          - text: "Hotéis Aliados"
            href: cronograma/hoteles-aliados/index-pt.qmd
          - text: "Equipe organizadora"
            href: sobre/equipo/index.qmd        
          - href: sobre/apoyo/apoio.qmd
          - href: sobre/coc/codigo-de-conduta.qmd
         # - href: sobre/ediciones-anteriores/edicoes-anteriores.qmd     
      - text: Programa
        menu:
      #     # - text: "Programaa resumido"
      #     #   href: cronograma/programa/preliminar.qmd 
      #      - text: "Programação de Palestras"
      #        href: cronograma/programa/index.qmd
          - text: "Palestras convidadas"
            href: cronograma/conferencistas/palestras-convidadas.qmd
          - text: "Workshops"
            href: cronograma/tutoriales/workshops-pt.qmd
          # - text: "R Dev Day"
          #   href: cronograma/r-dev-day/rdevday-pt.qmd      
          # - text: "Traslaton rOpenSci"
          #   href: cronograma/translaton/translaton-pt.qmd                  
          # - text: "Apresentações"
          #   href: cronograma/programa/presentaciones.qmd 
          # - text: "Pôsters"
          #   href: cronograma/programa/posters.qmd               
      - text: "Novidades"
        href: blog/pt/index.html   
      - text: Edições anteriores
        menu:
        - text: "2025"
          href: https://2025.latinr.org/
        - text: "2024"
          href: https://2024.latinr.org/
        - text: "2023"
          href: https://2023.latinr.org/
        - text: "2022"
          href: https://2022.latinr.org/
        - text: "2021"
          href: https://2021.latinr.org/
        - text: "2020"
          href: https://2020.latinr.org/
        - text: "2019"
          href: https://2019.latinr.org/
        - text: "2018"
          href: https://2018.latinr.org/