lang: es

format:
  html:
    include-in-header:
      text: |
        <style>.blog-section-en, .blog-section-pt { display: none !important; }</style>

project:
  output-dir: docs

website:
  navbar:
    left:
      - href: ./pt/index.html
        text: "PT"
      - href: ./en/index.html
        text: EN  
      - href: /index.html
        text: "**ES**"    
      - text: "Principal"
        href: /index.html
      - text: Sobre LatinR
        menu:        
          - text: "Equipo Organizador"
            href: sobre/equipo/index.qmd        
          - href: sobre/apoyo/index.qmd
          - href: sobre/coc/index.qmd
        #  - href: sobre/ediciones-anteriores/index.qmd  
      - text: Participa
        menu:
         - text: "Llamado a presentación de trabajos"
           href: blog/es/2026-03-27-presentacion-trabajos.html
         # - text: "Sobre la Inscripción"
         #   href: blog/es/2024-08-01-inscripcion.html 
      #   - text: "Inscripción"
       #    href: https://www.eventbrite.com.ar/e/1939670499679?
           
      # - text: LatinR 2026
      #   menu: 
      #     - text: "Lugar"
      #       href: cronograma/lugar/index.qmd 
      #     - text: "Recursos turísticos"
      #       href: cronograma/recursos-turisticos/index.qmd  
      #     - text: "Becas de asistencia"
      #       href: blog/es/2023-08-18-becas-2023.html    
      # - text: Programa
      #   menu:
      #     # - text: "Programa resumido"
      #     #   href: cronograma/programa/preliminar.qmd 
      #     - text: "Programa de Charlas y Conferencias"
      #       href: cronograma/programa/index.qmd
      #     - text: "Conferencistas"
      #       href: cronograma/conferencistas/index.qmd
      #     - text: "Tutoriales"
      #       href: cronograma/tutoriales/index.qmd
         # - text: "R Dev Day"
         #   href: cronograma/r-dev-day/index.qmd
         # - text: "Traslaton rOpenSci"
         #   href: cronograma/translaton/index.qmd                     
          # - text: "Presentaciones"
          #   href: cronograma/programa/presentaciones.qmd 
          # - text: "Posters"
          #   href: cronograma/programa/posters.qmd              
      - text: "Novedades"
        href: blog/es/index.html
      - text: "Conferencistas"
        href: cronograma/conferencistas/index.qmd
      - text: "Ediciones anteriores"
        menu:
        - text: "2025"
          href: https://2025.latinr.org/
        - text: "2024"
          href: https://2024.latinr.org/
        - text: "2023"
          href: https://2023.latinr.org/
        - text: "2022"
          href: https://2022.latinr.org/
        - text: "2021"
          href: https://2021.latinr.org/
        - text: "2020"
          href: https://2020.latinr.org/
        - text: "2019"
          href: https://2019.latinr.org/
        - text: "2018"
          href: https://2018.latinr.org/